# This is a basic workflow to help you get started with Actions

name: GithubExample

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Install elm, elm-format and cache the ELM_HOME directory
        uses: mpizenberg/elm-tooling-action@v1.2
        with:
          cache-key: elm-home-${{ hashFiles('elm-tooling.json', 'elm.json') }}

      # simple check that elm installed
      - name: validate elm is installed
        run: elm --version

      - name: make 9Birthdays
        run: elm make src/Main.elm   

      # elm-test is installed as well as run
      - name: run elm-test
        run: npx elm-test
