# This is a basic workflow to help you get started with Actions

name: GithubExample

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "carlhunterroach-gh-actions-exploration" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Elm tools and cache $ELM_HOME
        uses: mpizenberg/elm-tooling-action@v1.3
        with:
          cache-key: elm-home-${{ hashFiles('elm-tooling.json', 'elm.json') }}
          
      - name: validate elm is installed
        run: elm --version

      - name: install elm-test
        run: npx elm-test

  make:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: make 9Birthdays
        run: elm make src/Main.elm

  test:
    runs-on: ubuntu-latest
    needs: make
    steps:
      - name: test 9Birthdays
        run: elm-test
      
